version: '3.8'
services:
  vehicle_app:
    container_name: app
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
    - .:/usr/src/app
    - ./node_modules:/usr/src/app/node_modules
    - ./src/config:/usr/src/app/src/config
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - 5050:80
 
volumes: 
 data: {}
